name: CI Workflow
on: push
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Files
        run: ls -alrt

      - name: Build Project
        run: ./mvnw package