name: release workflow
on:
    workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
      snapshot-version:
        description: 'Next snapshot version'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'
  
jobs:
  release-project:
    runs-on: ubuntu-latest
    steps:
      - name: Release workflow
        run: |
          git init
          git config --global user.name "rishab-prasad"
          git config --global user.email "rishabprasad05@gmail.com"
         
       - name: clone the repository
         run: git clone https://github.com/rishab-prasad/my-project.git

       - name:  make a new branch 
         run: git branch branch2

       - name: Checkout 
         run: git checkout branch2

       - name: check maven version 
         run:  mvn --version

       - name: Update Release Version 
         run: mvn versions:set -DnewVersion=${{RELASE_VERSION}} -DgenerateBackupPoms=false -DprocessAllModules=true


       - name: Verify Build
         run:  mvn clean install


       - name: Commit Release Version Change
         run: |
          git add .
          git commit -m "Automated version update: ${{ RELEASE_VERSION}}"
          

        - name: Login in dockerhub
          run: docker login -u "${{secrets.DOCKERHUB_USERNAME}}"  -p "${{secrets.DOCKERHUB_PASSWORD}}" docker.io


        - name: Push Images
          run: docker push rishabprasad005/my-project    


         
       
 
 