name: release workflow
on:
    workflow_dispatch:
     inputs:
      RELEASE_VERSION:
        description: 'Version being released'
        required: true
      SNAPSHOT_VERSION:
        description: 'Next snapshot version'
        required: true
      BRANCH:
        description: 'Branch to release from'
        required: true
        default: 'master'
  
jobs:
  release-project:
    runs-on: ubuntu-latest
    steps:
       - name: Configure Git
         run: |
          git config --global user.name "rishab-prasad"
          git config --global user.email "rishabprasad05@gmail.com"
          
       - name: Checkout Code 
         uses: actions/checkout@v2
         with:
           ref: ${{github.events.inputs.BRANCH}}
           token: ${{ secrets.ACCESS_TOKEN }}
           path: code
           
       - name: list files
         run: ls -lrt

       - name: Update Release Version 
         run: cd code && ./mvnw versions:set -DnewVersion=${{github.events.inputs.RELEASE_VERSION}} -DgenerateBackupPoms=false -DprocessAllModules=true
     
       - name: Verify Build
         run: cd code && ./mvnw clean install
         
       - name: Commit Release Version Change
         run: |
          git add .
          git commit -m "Automated update to Release Version:: ${{ github.event.inputs.RELEASE_VERSION}}"
          git push origin ${{github.events.inputs.BRANCH}}

       - name: Create a git tag to the github repository
         run: cd code && git tag -a "${{github.events.inputs.RELEASE_VERSION}}" -m "Release ${{github.events.inputs.RELEASE_VERSION}} created by @$GITHUB_ACTOR"
 
       - name: Push tag ${{github.events.inputs.RELEASE_VERSION}}
         run: cd code && git push origin ${{github.events.inputs.RELEASE_VERSION}} 


         
       
 
 
