name: release workflow
on:
    workflow_dispatch:
     inputs:
      RELEASE_VERSION:
        description: 'Version being released'
        required: true
      SNAPSHOT_VERSION:
        description: 'Next snapshot version'
        required: true
      BRANCH:
        description: 'Branch to release from'
        required: true
        default: 'master'
  
jobs:
  release-project:
    runs-on: ubuntu-latest
    steps:
       - name: Configure Git
         run: |
          git config --global user.name "rishab-prasad"
          git config --global user.email "rishabprasad05@gmail.com"
          
       - name: Checkout Code 
         uses: actions/checkout@v2
         with:
           token: ${{ secrets.ACCESS_TOKEN }}
           
       - name: list files
         run: ls -lrt

       - name: Update Release Version 
         run: ./mvnw versions:set -DnewVersion=${{github.events.input.RELEASE_VERSION}} -DgenerateBackupPoms=false -DprocessAllModules=true
     
       - name: Verify Build
         run: ./mvnw clean install

       - name: Create a git tag to the github repository
         run: git tag -a "${{github.events.input.RELEASE_VERSION}}" -m "Release ${{github.events.input.RELEASE_VERSION}} created by @$GITHUB_ACTOR"
 
       - name: Push tag ${{github.events.input.RELEASE_VERSION}}
         run: git push origin ${{github.events.input.RELEASE_VERSION}} 

      # - name: Commit Release Version Change
       #  run: |
        #  git add .
         # git commit -m "Automated version update: ${{github.events.input.RELEASE_VERSION}}"
          
  #      - name: Login in dockerhub
   #       run: docker login -u "${{secrets.DOCKERHUB_USERNAME}}"  -p "${{secrets.DOCKERHUB_PASSWORD}}" docker.io
#

 #       - name: Push Images
  #        run: docker push rishabprasad005/my-project    


         
       
 
 
