name: Skip Run Based On Label
on: 
  pull_request:
    branches:
      - master
      
on:
  pull_request:
    types: [labeled]
    branches: [master]

jobs:
  build:
    if: ${{ github.event.label.name == 'DO NOT MERGE' }}
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
