name: Skip Run Based On Label
on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    #if: ${{ github.event.label.name == 'DO NOT MERGE' }}
    if: ${{ !contains(github.event.*.labels.*.name, 'DO NOT MERGE') }}
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Dump GitHub context
      env:
          GITHUB_EVENT_CONTEXT: ${{ toJSON(github.event.*.labels.*.name) }}
      run: echo "$GITHUB_EVENT_CONTEXT"
