name: Skip Run Based On Label
on: 
  pull_request:
    branches:
      - master

jobs:
  build-project:
    if: github.repository_owner == 'rishab-prasad' && !contains(github.event.*.labels.*.name, 'DO NOT MERGE')
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      env:
        with: ${{ !contains(github.event.*.labels.*.name, 'DO NOT MERGE') }}
        without: ${{ contains(github.event.*.labels.*.name, 'DO NOT MERGE') }}
      run: |
        echo $with
        echo $without
      
    - name: Dump GitHub context
      env:
          GITHUB_EVENT_CONTEXT: ${{ toJSON(github.event.*.labels.*.name) }}
      run: echo "$GITHUB_EVENT_CONTEXT"
