name: Test Workflow Disptach Input Options

on: 
  workflow_dispatch:
  
  
jobs:
  release-macos-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
           token: ${{ secrets.ACCESS_TOKEN }}
           repository: Apicurio/apicurio-registry-examples
           event-type: on-registry-updated
