name: Test Workflow 

on: 
  workflow_dispatch:
  
  
jobs:
  install-syft:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        
      - name: print syft version
        run: syft --version

      - name: Login to registry.redhat.io
        run: docker login -u "apicurio" -p "${{ secrets.APICURIO_RED_HAT_PASSWORD }}" registry.redhat.io
        
      - name: Generate SBOM
        run: |
          syft docker:registry.redhat.io/integration/service-registry-sql-rhel8:latest -o table=sql-sbom
          syft docker:registry.redhat.io/integration/service-registry-kafkasql-rhel8:latest -o table=kafkasql-sbom
          syft docker:registry.redhat.io/integration/service-registry-rhel8-operator:latest -o table=operator-sbom
          cat sql-sbom
